apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-http-listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-http-listener
  template:
    metadata:
      labels:
        app: my-http-listener
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: my-http-listener
        image: mendhak/http-https-echo:26
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: HTTPS_PORT
          value: "8443"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8443
          name: https
