apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: my-http-listener
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: https
    protocol: TCP
    port: 8443
    targetPort: 8443